language: php

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install php --version 8.0
        - choco install composer
        - choco install ffmpeg
        - export PATH="/c/tools/php80:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
        - composer self-update
        - sed -i s/\;extension=gd/extension=gd/ /c/tools/php80/php.ini
        - sed -i s/\;extension=fileinfo/extension=fileinfo/ /c/tools/php80/php.ini

    - php: '8.0'
    - php: '8.0'
      name: 'Prefer lowest'
      install:
        - composer update --no-interaction --prefer-lowest
    - php: 'nightly'
  allow_failures:
    - php: 'nightly'

env:
  global:
    - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.cache/composer/files

addons:
  apt:
    packages:
      - php-xml
      - php-mysql
      - php-gd
      - php-curl


install:
  - composer install --no-interaction

before_script:
  - vendor/bin/phpunit --version

script:
  - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)