#!/usr/bin/php
<?php

use datagutten\descriptionMaker;
use datagutten\descriptionMaker\MusicBrainzDescription;
use datagutten\tools\files\files;


require $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

$desc = descriptionMaker\DescriptionMakers::album($argv[1], ['flac']);

$mb=new MusicBrainzDescription;
$file = files::first_file($argv[1]);
$info=pathinfo($argv[1]);

try
{
	$mediainfo = descriptionMaker\Mediainfo::plain($file);
	$mediainfo_file = files::path_join($info['dirname'], $info['filename'] . '.mediainfo');
	file_put_contents($mediainfo_file, $mediainfo);
}
catch (descriptionMaker\exceptions\DescriptionException|FileNotFoundException $e)
{
	echo $e->getMessage()."\n";
}

$file_description = descriptionMaker\utils::description_file($argv[1]);

file_put_contents($file_description,$desc); //Write the complete description to a file
printf("Description saved as %s\n", $file_description);

