#!/usr/bin/php
<?php

use datagutten\descriptionMaker\Mediainfo;
use datagutten\tools\files\files;

require __DIR__.'/loader.php';

if(!file_exists($argv[1]))
    die("File not found\n");

$mediainfo_file = files::path_join(dirname($argv[1]), basename($argv[1])) . '.mediainfo';
file_put_contents($mediainfo_file, Mediainfo::plain($argv[1])); //Write mediainfo to a file
printf("Mediainfo created as %s\n", $mediainfo_file);