#!/usr/bin/php
<?php

use datagutten\tools\files\files;

require __DIR__.'/loader.php';

$tools = new description();
$desc = new description;
if(!file_exists($argv[1]))
    die("File not found\n");

$mediainfo_file = files::path_join(dirname($argv[1]), basename($argv[1])) . '.mediainfo';
file_put_contents($mediainfo_file, $desc->simplemediainfo($file)); //Write mediainfo to a file
printf("Mediainfo created as %s\n", $mediainfo_file);