#!/usr/bin/php
<?php

use datagutten\descriptionMaker;
use datagutten\tools\files\files;

require __DIR__ . '/loader.php';

$desc = new description(descriptionmaker_config());

try
{
    $video_file = $argv[1];
    $folder = files::path_join(dirname($video_file), 'snapshots');
    echo $desc->snapshots->snapshots($video_file, $folder);
}
catch (descriptionMaker\exceptions\SnapshotException $e)
{
    printf("Error uploading or creating snapshots: %s\n%s\n", $e->getMessage(), $e->getTraceAsString());
}