#!/usr/bin/php
<?php

use datagutten\descriptionMaker;
use datagutten\tools\files\files;
use datagutten\tvdb;


require $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

$config = descriptionmaker_config();
$desc = new description($config);
if(isset($config['tvdb_cache']))
    $tvdb_scrape = new tvdb\cache\TVDBScrape($config['tvdb_cache']);
else
    $tvdb_scrape = new tvdb\TVDBScrape();


$options = [
    ['p', 'path', GetOpt\GetOpt::REQUIRED_ARGUMENT, 'File or folder to create description for'],
    ['s', 'slug', GetOpt\GetOpt::OPTIONAL_ARGUMENT, 'TVDB slug'],
    ['l', 'lang', GetOpt\GetOpt::OPTIONAL_ARGUMENT, 'Language'],
    ['o', 'order', GetOpt\GetOpt::OPTIONAL_ARGUMENT, 'Episode ordering (defaults to official)']];

$getOpt = new GetOpt\GetOpt($options);
// process arguments and catch user errors
try
{
    try
    {
        $getOpt->process();
    }
    catch (GetOpt\ArgumentException\Missing $exception)
    {
        // catch missing exceptions if help is requested
        if (!$getOpt->getOption('help'))
        {
            throw $exception;
        }
    }
}
catch (GetOpt\ArgumentException $exception)
{
    echo 'help';
    file_put_contents('php://stderr', $exception->getMessage() . PHP_EOL);
    echo PHP_EOL . $getOpt->getHelpText();
    exit;
}
foreach ($getOpt->getOptionObjects() as $option)
{
    if ($option->getMode() == GetOpt\GetOpt::REQUIRED_ARGUMENT && $option->getValue() == null)
    {
        file_put_contents('php://stderr', 'Missing required argument ' . $option->getName() . PHP_EOL);
        die(PHP_EOL . $getOpt->getHelpText());
    }
}


$path = $getOpt->getOption('path');
$pathinfo = pathinfo($path);
if (is_dir($path))
{
    $pathinfo['filename'] = $pathinfo['basename'];
    $pathinfo['extension'] = null;
}

$info = descriptionMaker\TVSeriesUtils::parse_release($pathinfo['filename']);
if (empty($info))
    die("Unable to parse series name\n");

$tvdb_desc = new descriptionMaker\TVDB();
$tvdb_slug = $getOpt->getOption('slug');

try
{
    if(!empty($tvdb_slug))
    {
        $series = $tvdb_scrape->series($tvdb_slug, $getOpt->getOption('lang'));
        $banners = $series->banners();
    }
}
catch (tvdb\exceptions\tvdbException $e)
{
    echo 'Error from TVDB API: ' . $e->getMessage() . "\n";
}

$description = '';

if (!empty($banners)) //Series banner
    $description .= descriptionMaker\BBCode::image($banners[0], sprintf('https://www.thetvdb.com/series/%s', $tvdb_slug)) . "\n";
else //In case the series is not found or don't have a banner, use the series name as banner
    $description .= descriptionMaker\BBCode::simple('b', $pathinfo['filename'])."\n";

if (!empty($search['overview'])) //Series overview
    $description .= $search['overview'] . "\n\n";

if (!empty($series))
{
    $season = $series->season($info['season'], $getOpt->getOption('order') ?? 'official');
    if (empty($info['episode'])) //Complete season
        $description .= $tvdb_desc->episode_list($season);
    else //Single episode
        $description .= $tvdb_desc->episode($season->episode($info['episode'])) . "\n\n";
}

if (is_file($path))
    $video_file = realpath($path);
elseif (is_dir($path))
    $video_file = files::first_file($path, array('mkv', 'ts', 'mp4')); //TODO: Check mime type
else
    die("Video file not found\n");

try
{
    $folder = files::path_join($pathinfo['dirname'], 'snapshots');
    if(!empty($desc->snapshots))
        $description .= $desc->snapshots->snapshots($video_file, $folder);
    else
        trigger_error('Image host class not set, unable to create snapshots');
}
catch (descriptionMaker\exceptions\SnapshotException $e)
{
    printf("Error uploading or creating snapshots: %s\n%s\n", $e->getMessage(), $e->getTraceAsString());
}

try
{
	$mediainfo = descriptionMaker\Mediainfo::plain($video_file);
	$mediainfo_file = files::path_join($pathinfo['dirname'], $pathinfo['basename'] . '.mediainfo');
	file_put_contents($mediainfo_file, $mediainfo);
}
catch (descriptionMaker\exceptions\DescriptionException|FileNotFoundException $e)
{
    echo $e->getMessage()."\n";
}

$desc_file = files::path_join($pathinfo['dirname'], $pathinfo['filename'] . '.txt');
file_put_contents($desc_file, $description);
printf("Description saved as %s\n", $desc_file);